### ISSUE TITLE
Lollypop

### ISSUE THREAD

**Issue by cloudsun9** [Rayzr522/now-clocking#5]
Any chance of Lollypop support?
Would be nice, Thanks.

**Comment by foxfirecodes** [comment]
I don't have any current plans for this, but you're welcome to create a PR for this yourself. otherwise I can try and remember to add it when i have free time but my life keeps me quite busy, sadly.

looks like Lollypop supports mpris stuff so adding it should basically be just copying and pasting the VLC code and changing it to look for Lollypop
